# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
    unused_element: warning
    missing_return: warning
    invalid_assignment: warning
    unused_field: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_asserts_with_message: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_constructors_over_static_methods: warning
    prefer_expression_function_bodies: warning
    prefer_final_fields: warning
    prefer_for_elements_to_map_fromIterable: warning
    prefer_inlined_adds: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_iterable_whereType: warning
    prefer_single_quotes: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_lambdas: warning
    unnecessary_new: warning
    unnecessary_this: warning
    unrelated_type_equality_checks: warning
    unnecessary_getters_setters: warning
    always_declare_return_types: warning
    unnecessary_non_null_assertion: warning
    invalid_null_aware_operator: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_parenthesis: warning
    always_require_non_null_named_parameters: warning
    unused_catch_clause: warning
    unused_catch_stack: warning
    constant_identifier_names: warning
    omit_local_variable_types: warning
    avoid_unused_constructor_parameters: warning
    avoid_empty_else: warning
    prefer_if_null_operators: warning
    prefer_void_to_null: warning
